context:
  name: bionty
  version: "1.8.0"
  python_min: '3.10'

package:
  name: ${{ name|lower }}
  version: ${{ version }}

source:
  url: https://pypi.org/packages/source/${{ name[0] }}/${{ name }}/bionty-${{ version }}.tar.gz
  sha256: 00c5e8610aa762f602675ba7db07fd351d4ced40dccef8536f4d8180b24bd2e6

build:
  number: 0
  noarch: python
  script: ${{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation

requirements:
  host:
    - python ${{ python_min }}.*
    - flit-core >=3.2,<4
    - pip
  run:
    - python >=${{ python_min }}
    - lamindb >=1.8.1
    - lamindb_setup >=0.81.2
    - lamin_utils >=0.13.9
    - requests
    - pyyaml

tests:
  - python:
      imports:
        - bionty
      pip_check: true
      python_version: ${{ python_min }}.*

about:
  summary: Basic biological entities, coupled to public ontologies [`source <https://github.com/laminlabs/bionty/blob/main/bionty/models.py>`__].
  license: Apache-2.0
  license_file: LICENSE
  homepage: https://github.com/laminlabs/bionty

extra:
  recipe-maintainers:
    - hadim
